In [1]:
import numpy as np
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
a=np.array([1,3,5],dtype=complex)
print(a)
b=np.array([[1,2],[1,6]])
print(b)

[1.+0.j 3.+0.j 5.+0.j]
[[1 2]
 [1 6]]


In [7]:
dt = np.dtype([('age',np.int8)]) 
# int8, int16, int32, int64 四种数据类型可以使用字符串 'i1', 'i2','i4','i8' 代替
print(dt)
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a['age'])

[('age', 'i1')]
[10 20 30]


In [12]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a['age'])

[21 18]


b	布尔型
i	(有符号) 整型
u	无符号整型 integer
f	浮点型
c	复数浮点型
m	timedelta（时间间隔）
M	datetime（日期时间）
O	(Python) 对象
S, a	(byte-)字符串
U	Unicode
V	原始数据 (void)

In [17]:
x = np.empty([3,2], dtype = int) 
print (x)
y = np.zeros((5,), dtype = np.int) 
print(y)
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)

[[4607182418800017408                   0]
 [4613937818241073152                   0]
 [4617315517961601024                   0]]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
